- name: Install server 
  hosts: all
  gather_facts: true
  tasks:
    - name: Install httpd
      when: ansible_facts['distribution'] == 'CentOS'
      block:
        - yum:
            name: httpd
            state: present
        - service:
            name: httpd
            state: started
      rescue:
        - debug:  
            msg: "Playbook has failed for {{ inventory_hostname}}  node"

